name: Generate GitHub contribution snake

# Quando rodar
on:
  schedule:
    # a cada 12 horas (ajuste se quiser)
    - cron: '0 */12 * * *'
  workflow_dispatch: {}    # permite rodar manualmente pela aba Actions
  push:
    branches:
      - main

permissions:
  contents: write   # necessário para o action pushar para a branch output

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout (needed for some steps)
        uses: actions/checkout@v4

      - name: Generate SVG and dark SVG (svg-only)
        # usa a versão estável do Platane/snk para gerar apenas SVG (rápido)
        uses: Platane/snk/svg-only@v3
        with:
          # usa o dono do repositório (no seu caso: CoimbraDouglas)
          github_user_name: ${{ github.repository_owner }}
          # quais outputs queremos; gera SVG normal e versão dark com palette
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated files to output branch
        # action para push fácil para uma branch (vai criar a branch se não existir)
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
